version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    target-branch: "develop"
    assignees:
      - ursinn
  - package-ecosystem: maven
    directory: "/bukkit/"
    schedule:
      interval: daily
    target-branch: "develop"
    assignees:
      - ursinn
  - package-ecosystem: maven
    directory: "/spigot/"
    schedule:
      interval: daily
    target-branch: "develop"
    assignees:
      - ursinn
  - package-ecosystem: maven
    directory: "/bungee/"
    schedule:
      interval: daily
    target-branch: "develop"
    assignees:
      - ursinn